server:
  port: 8084

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input:
          group: kafka-sample
          destination: input_topic
          contentType: application/json
        output:
          destination: output_topic
          contentType: application/json